apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-pipeline-deployment
  labels:
    app: ci-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-pipeline
  template:
    metadata:
      labels:
        app: ci-pipeline
    spec:
      containers:
      - name: ci-pipeline-container
        image: siri037/ci-pipeline:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ci-pipeline-service
spec:
  selector:
    app: ci-pipeline
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
