apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    version: blue  # Change this to "green" to switch traffic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
